name: new_collecteur_ui
description: "The soft's collector app"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  fluent_ui: ^4.12.0
  window_manager: ^0.5.1
  syncfusion_flutter_xlsio: ^30.1.40
  flutter_dotenv: ^5.2.1
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
