name: Build Windows Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'
          channel: 'stable'

      - name: Write secrets to .env file (pre-build)
        run: |
          echo "COLLECTOR_SECRET=${{ secrets.COLLECTOR_SECRET }}" > .env
          echo "CODE=${{ secrets.CODE }}" >> .env
          echo "HOST=${{ secrets.HOST }}" >> .env

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows Executable
        run: flutter build windows --release
      
      - name: Write secrets to build artifact .env files (post-build)
        run: |
          mkdir -p build\windows\x64\runner\Release\data\flutter_assets
          echo "COLLECTOR_SECRET=${{ secrets.COLLECTOR_SECRET }}" > build\windows\x64\runner\Release\data\.env
          echo "CODE=${{ secrets.CODE }}" >> build\windows\x64\runner\Release\data\.env
          echo "HOST=${{ secrets.HOST }}" >> build\windows\x64\runner\Release\data\.env
          echo "COLLECTOR_SECRET=${{ secrets.COLLECTOR_SECRET }}" > build\windows\x64\runner\Release\data\flutter_assets\.env
          echo "CODE=${{ secrets.CODE }}" >> build\windows\x64\runner\Release\data\flutter_assets\.env
          echo "HOST=${{ secrets.HOST }}" >> build\windows\x64\runner\Release\data\flutter_assets\.env
        shell: bash

      - name: Compress .exe to ZIP
        run: |
          $ErrorActionPreference = "Stop"
          $buildDir = "build\windows\x64\runner\Release"
          $exe = Join-Path $buildDir "collecteur_soft.exe"
          $zip = "collecteur-executable.zip"
          choco install 7zip -y
          & "C:\Program Files\7-Zip\7z.exe" a -tzip "$zip" "$exe"
        shell: pwsh

      - name: Upload ZIP Artifact
        uses: actions/upload-artifact@v4
        with:
          name: collecteur-executable
          path: collecteur-executable.zip
